import Link from "next/link";

export const metadata = {
  title: "Terms of Service -- Smart Repute",
};

export default function TermsOfService() {
  return (
    <main className="min-h-screen bg-[#FAFAF8] text-[#0B0C10]">
      <div className="mx-auto max-w-2xl px-6 py-16 md:px-10 md:py-24">
        <Link
          href="/"
          className="text-sm text-[#3552FF] hover:underline"
        >
          &larr; Smart Repute
        </Link>

        <h1 className="mt-6 text-3xl font-bold tracking-[-0.02em] md:text-4xl">
          Terms of Service
        </h1>

        <p className="mt-2 text-sm text-[#63666D]">
          Last updated: October 2, 2026
        </p>

        <div className="mt-10 flex flex-col gap-8 text-[15px] leading-7 text-[#0B0C10]/90">
          <section>
            <h2 className="text-lg font-semibold">
              Agreement
            </h2>
            <p className="mt-2">
              These terms govern your use of Smart Repute
              (&quot;the service&quot;). By connecting your Google
              Business Profile, you agree to these terms on behalf
              of yourself and the business you&apos;re authorized
              to represent.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold">
              What you&apos;re authorizing
            </h2>
            <p className="mt-2">
              By connecting your Google Business Profile, you
              authorize Smart Repute to read your business&apos;s
              Google reviews and to post replies to Google on your
              behalf -- but only for the specific replies you
              review and approve yourself. We never post a reply
              you have not approved.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold">
              AI-generated content
            </h2>
            <p className="mt-2">
              Reply drafts are generated by AI based on the
              review&apos;s content and star rating. You are
              responsible for reviewing each draft before approving
              it -- including checking it is accurate, appropriate,
              and does not disclose anything you don&apos;t want
              made public. Smart Repute is not responsible for the
              content of a reply you chose to approve and post.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold">
              Your responsibilities
            </h2>
            <p className="mt-2">
              You must have the authority to manage the Google
              Business Profile you connect. You&apos;re responsible
              for complying with Google&apos;s own policies for
              Business Profiles and reviews, including not using
              review-request tools to selectively solicit reviews
              only from customers you expect to leave positive
              feedback.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold">
              Disconnecting
            </h2>
            <p className="mt-2">
              You can disconnect your Google account at any time
              from within the product. This immediately revokes
              our access to your Business Profile and deletes your
              stored access token.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold">
              Availability
            </h2>
            <p className="mt-2">
              Smart Repute is provided on an &quot;as is&quot;
              basis. We do our best to keep the service available
              and accurate but don&apos;t guarantee it will be
              uninterrupted or error-free, including when the
              interruption is caused by Google&apos;s or our AI
              provider&apos;s own systems being unavailable.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold">
              Changes to the service or these terms
            </h2>
            <p className="mt-2">
              We may update these terms or the service over time.
              If we make material changes to these terms, we&apos;ll
              ask you to re-accept them before continuing to use
              the product.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold">
              Contact
            </h2>
            <p className="mt-2">
              Questions about these terms can be sent to drabhinavrao2000@gmail.com
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
